import type { NextPage } from "next";
import Head from "next/head";
import { Row } from "src/Components/Row";
import styles from "src/styles/Home.module.css";
import { requests } from "src/Components/request";

const Home: NextPage = () => {
	return (
		<div className={styles.container}>
			<Head>
				<title>PortFolio for TypeScript</title>
				<meta name="description" content="Generated by create next app" />
				<link rel="icon" href="/favicon.ico" />
			</Head>
			<div className="">
				<Row
					title="NETFLIX ORIGUINALS"
					fetchUrl={requests.feachNetflixOriginals}
					isLargeRow
				/>
				<Row title="Top Rated" fetchUrl={requests.feactTopRated} />
				<Row title="Action Movies" fetchUrl={requests.feactActionMovies} />
				<Row title="Comedy Movies" fetchUrl={requests.feactComedyMovies} />
				<Row title="Horror Movies" fetchUrl={requests.feactHorrorMovies} />
				<Row title="Romance Movies" fetchUrl={requests.feactRomanceMovies} />
				<Row title="DOcumentaries" fetchUrl={requests.feactDocumentMovies} />
			</div>
		</div>
	);
};

export default Home;
